version: '3.8'

services:
  # 后端服务 (NestJS)
  backend:
    build:
      context: ../apps/server
      dockerfile: Dockerfile.prod
    container_name: decode-backend-prod
    ports:
      - "${BACKEND_PORT:-4000}:${BACKEND_PORT:-4000}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${BACKEND_PORT:-4000}
      - DATABASE_URL=${DATABASE_URL:-mongodb://mongodb:27017/decode}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret}
      - API_PREFIX=${API_PREFIX:-api}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    restart: always
    networks:
      - decode-network

  # 前端服务 (React)
  frontend:
    build:
      context: ../apps/admin
      dockerfile: Dockerfile.prod
    container_name: decode-frontend-prod
    ports:
      - "${FRONTEND_PORT:-80}:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:4000}
      - REACT_APP_ENV=${NODE_ENV:-production}
    depends_on:
      - backend
    restart: always
    networks:
      - decode-network

  # 数据库服务 (MongoDB)
  mongodb:
    image: mongo:${MONGODB_VERSION:-6.0}
    container_name: decode-mongodb-prod
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE:-decode}
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - decode-network

volumes:
  mongodb_data:

networks:
  decode-network:
    driver: bridge